### ISSUE TITLE
Sign invalid

### ISSUE THREAD

**Issue by PatalJunior** [Octoober/tuya-bulb-control#3]
Error in signature, so can't won't work.

**Comment by PatalJunior** [comment]
File "C:\Users\eduar\AppData\Local\Programs\Python\Python311\Lib\site-packages\tuya_bulb_control-0.1b4-py3.11.egg\tuya_bulb_control\_tuya_api.py", line 102, in __token
    raise AuthorizedError(
tuya_bulb_control.exceptions.AuthorizedError: 1004 -> Sign invalid

**Comment by orpos** [comment]
i sucefully updated the sign header and got it to work, i will try to make a pr to fix the error

**Comment by orpos** [comment]
my tuya license expired and i cannot pay it so i cannot debug the new issue(#5 ) about this 😔
